### ISSUE TITLE
Allow include/exclude arrays to include either strings or objects

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/enterprise-contract-controller#191]
In [HACBS-2599](https://issues.redhat.com/browse/HACBS-2599), we came up with the idea to allow policy config authors to specify when a certain include/exclude line is effective. This is issue is about implementing the supporting CRD changes.

Change the schema of [SourceConfig](https://github.com/enterprise-contract/enterprise-contract-controller/blob/ee994416688e9b22dc657987537279095572aaae/api/v1alpha1/enterprisecontractpolicy_types.go#L75-L85) to allow items of the `Exclude` and `Include` lists to be either a string (as it is today), or an an object (new requirement).

The object should contain the following attributes:

```
Name           string (json "name")
EffectiveOn    string (json "effectiveOn")
EffectiveUntil string (json "effectiveUntil")
```

Both `EffectiveOn` and `EffectiveUntil` should conform to [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339), e.g. `2022-11-18T00:00:00Z`. If it's possible to enforce this on the CRD side, great, but it's not a requirement. Be sure to document the expected format regardless.

For inspiration, this is a similar approach to the one taken in Tekton's [ParamType](https://github.com/tektoncd/pipeline/blob/e8b85e2e084e2b952ab985543c470c1ac0d430db/pkg/apis/pipeline/v1/param_types.go#L408).

**Comment by zregvart** [comment]
We cannot make this change without bumping the API version. The reason why this works for Tekton CRs is because they're schemaless.
